Repository nickkolok/chas-ege, pull requests merged in 2023-12, with the labels that each got.

#1311 Склонение 'транспортное средство'
  lib/lxsoch.js
Labels: Склонялка

#1310 Задача 63 ФИПИ #1303
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
  zdn/matege2024p/10/99607.js
Labels: шаблон, разработка

#1296 Задача про мячик и косинус #1275
  zdn/matege2023p/8/fipi.js
  zdn/matege2023p/8/main.js
  zdn/matege2024p/9/28003.js
Labels: шаблон, разработка, Задачи с прикладным содержанием

#1301 Рефакторинг 11.js #1298
  zdn/mat2014/B12/11.js
Labels: шаблон, Больше вариантов!, Баг, Улучшение, Задачи с прикладным содержанием

#1307 [new] [zdn] - newTask_99574
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
  zdn/matege2024p/10/99574.js
Labels: Текстовые задачи, Задачи на проценты сплавы и смеси
