Repository nickkolok/chas-ege, pull requests merged in 2023-09, with the labels that each got.

#1121 [core] A patch to avoid two absolutely identical tasks directly one-by-one
  lib/core_dvig.js
Labels: Принимаем

#1122 [sh] Print shell - add an option to restrict task deduplication to inside one variant
  sh/pechmat.html
  sh/pechmat.js
Labels: Принимаем

#1186 [lib] String.allDecimalsToStandard()
  lib/string.js
Labels: Принимаем

#1160 [zdn][WIP] mat2014/B10/4 - refactoring
  zdn/mat2014/B10/4.js
Labels: Требует доработки, Куб

#1159 [zdn][WIP] mat2014/B10/9 - colors
  zdn/mat2014/B10/9.js
Labels: Требует доработки, Куб

#1158 [zdn][WIP] mat2014/B10/3 - colors
  zdn/mat2014/B10/3.js
Labels: Требует доработки, Куб

#1189 newTask_644849
  zdn/matege2024p/2/644849.js
Labels: Вектора

#1184 newTask_64485001
  zdn/matege2024p/2/64485001.js
  zdn/matege2024p/2/main.js
Labels: Вектора

#1183 newTask_27741
  zdn/matege2024p/2/27741.js
  zdn/matege2024p/2/main.js
Labels: Вектора

#1037 [zdn][fix] zdn/misc_progressions/15/1.js - avoid false accuracy - .ts()
  zdn/misc_progressions/15/1.js
Labels: Принимаем

#1213 newTask_687657781
  zdn/matege2024p/2/687657781.js
  zdn/matege2024p/2/main.js
Labels: Вектора

#1209 newTask_644544196
  zdn/matege2024p/2/644544196.js
  zdn/matege2024p/2/main.js
Labels: Вектора
