Repository nickkolok/chas-ege, pull requests merged in 2024-10, with the labels that each got.

#1628 Newtask 311438
  zdn/matoge2024/9/311438.js
Labels: ОГЭ, разработка, Уравнения и системы уравнений

#1449 genAssert Graph Crosses Vertical and Horizontal
  lib/func.js
  lib/func_assert.js
Labels: библиотека

#1679 Newtask 523375
  zdn/matege2024p/10/523375.js
  zdn/matege2024p/10/fipi.js
  zdn/matege2024p/10/main.js
Labels: ЕГЭ-профиль, разработка, Текстовые задачи

#1675 Newtask 26590
  zdn/matege2024p/10/26590.js
  zdn/matege2024p/10/fipi.js
  zdn/matege2024p/10/main.js
Labels: ЕГЭ-профиль, разработка, Текстовые задачи

#1678 Newtask 27482
  zdn/matege2024p/10/27482.js
  zdn/matege2024p/10/fipi.js
  zdn/matege2024p/10/main.js
Labels: ЕГЭ-профиль, разработка, Текстовые задачи

#1677 Newtask 26588
  zdn/matege2024p/10/26588.js
  zdn/matege2024p/10/fipi.js
  zdn/matege2024p/10/main.js
Labels: ЕГЭ-профиль, разработка, Текстовые задачи

#1676 Newtask 26586
  zdn/matege2024p/10/26586.js
  zdn/matege2024p/10/fipi.js
  zdn/matege2024p/10/main.js
Labels: ЕГЭ-профиль, разработка, Текстовые задачи
