Repository nickkolok/chas-ege, pull requests merged in 2024-02, with the labels that each got.

#1333 Задача 28009 РешуЕГЭ [close #1300]
  zdn/matege2023p/8/fipi.js
  zdn/matege2023p/8/main.js
  zdn/matege2024p/9/28009.js
Labels: шаблон, ЕГЭ-профиль, разработка, Задачи с прикладным содержанием

#1326 Задача 99614 РешуЕГЭ (177 #1303)
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
  zdn/matege2024p/10/99614.js
Labels: шаблон, ЕГЭ-профиль, разработка, Текстовые задачи

#1316 Задача про обогрев помещения #1273 (rebase на основную ветку, правки)
  zdn/matege2023p/8/fipi.js
  zdn/matege2023p/8/main.js
  zdn/matege2024p/9/27995.js
Labels: шаблон, разработка, Задачи с прикладным содержанием

#1327 Задача 26597 РешуЕГЭ (167,171 #1303)
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
  zdn/matege2024p/10/26597.js
Labels: шаблон, ЕГЭ-профиль, разработка, Текстовые задачи

#1332 Задача 28012 РешуЕГЭ #1299
  zdn/matege2023p/8/fipi.js
  zdn/matege2023p/8/main.js
  zdn/matege2024p/9/28012.js
Labels: шаблон, ЕГЭ-профиль, разработка, Задачи с прикладным содержанием

#1328 Задача 99619 РешуЕГЭ (173 #1303)
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
  zdn/matege2024p/10/99619.js
Labels: шаблон, ЕГЭ-профиль, разработка, Текстовые задачи

#1317 Задача про водолазный колокол (№27996) #1274 (ребейз на основную ветку + правки)
  zdn/matege2023p/8/fipi.js
  zdn/matege2023p/8/main.js
  zdn/matege2024p/9/27996.js
Labels: шаблон, разработка, Задачи с прикладным содержанием

#1288 newTask_911
  zdn/matege2024p/3/911.js
  zdn/matege2024p/3/fipi.js
  zdn/matege2024p/3/main.js
Labels: Пирамиды, Стереометрия

#1291 newTask_324450
  zdn/matege2024p/3/324450.js
  zdn/matege2024p/3/fipi.js
  zdn/matege2024p/3/main.js
Labels: Пирамиды, Стереометрия

#1290 newTask_27109
  zdn/matege2024p/3/27109.js
  zdn/matege2024p/3/fipi.js
  zdn/matege2024p/3/main.js
Labels: Пирамиды, Стереометрия

#1212 newTask_64485007
  zdn/matege2024p/2/64485007.js
  zdn/matege2024p/2/main.js
Labels: Вектора

#1289 newTask_168
  zdn/matege2024p/3/168.js
  zdn/matege2024p/3/fipi.js
  zdn/matege2024p/3/main.js
Labels: Пирамиды, Стереометрия

#1207 refactoring_2/11
  zdn/mat2014/B5/11.js
Labels: Вектора

#1149 newTask_27589
  zdn/matege2023p/1/27589.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия

#1141 newTask_173
  zdn/matege2023p/1/173.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Окружность, Четырёхугольник

#1269 newTask_36
  zdn/matege2024p/3/36.js
  zdn/matege2024p/3/fipi.js
  zdn/matege2024p/3/main.js
Labels: Параллелепипеды, Стереометрия

#1145 newTask_153
  zdn/matege2023p/1/153.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Окружность, Четырёхугольник

#1146 newTask_169
  zdn/matege2023p/1/169.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Окружность, Четырёхугольник

#1125 newTask_2069
  zdn/matege2023p/1/2069.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия, Прямоугольный треугольник

#1126 newTask_6080
  zdn/matege2023p/1/6080.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия, Прямоугольный треугольник

#1128 NewTask_27764
  zdn/matege2023p/1/27764.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия

#1129 NewTask_5541
  zdn/matege2023p/1/5541.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия, Прямоугольный треугольник

#1131 newTask_2066
  zdn/matege2023p/1/2066.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия

#1132 newTask_5941
  zdn/matege2023p/1/5941.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Параллелограмм

#1130 NewTask_1945
  zdn/matege2023p/1/1945.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия

#1137 NewTask 92
  zdn/matege2023p/1/92.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Параллелограмм

#1138 newTask_27758
  zdn/matege2023p/1/27758.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия

#1140 newTask_181
  zdn/matege2023p/1/181.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Окружность, Четырёхугольник

#1143 newTask_125
  zdn/matege2023p/1/125.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Окружность

#1147 newTask_99
  zdn/matege2023p/1/99.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия

#1139 newTask_185
  zdn/matege2023p/1/185.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия, Окружность

#1144 newTask_131
  zdn/matege2023p/1/131.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Окружность

#1136 newTask 4850
  zdn/matege2023p/1/4850.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Параллелограмм

#1393 Задача 27984 РешуЕГЭ [close #1354]
  zdn/matege2023p/8/fipi.js
  zdn/matege2023p/8/main.js
  zdn/matege2024p/9/27984.js
Labels: шаблон, ЕГЭ-профиль, разработка, Задачи с прикладным содержанием

#995 NewTask_500246
  zdn/matege2023p/1/500246.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия

#1127 NewTask_27762
  zdn/matege2023p/1/27762.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия

#1134 NewTask 3353
  zdn/matege2023p/1/3353.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Ромб

#1142 newTask_119&121
  zdn/matege2023p/1/119.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Планиметрия, Окружность

#1148 newTask_27592
  zdn/matege2023p/1/27592.js
  zdn/matege2023p/1/fipi.js
  zdn/matege2023p/1/main.js
Labels: Треугольники, Планиметрия, Трапеция
