Repository nickkolok/chas-ege, pull requests merged in 2024-12, with the labels that each got.

#1659 cutted
  lib/func.js
Labels: ЕГЭ-профиль, библиотека

#1776 [zdn] [new] - 320181
  zdn/matege2023p/3/fipi.js
  zdn/matege2023p/3/main.js
  zdn/matege2024p/4/320181.js
Labels: Теория вероятности(простая)

#1778 [lib] [fix] - Белоруссия -> Белорусь
  lib/osnmas.js
Labels: Склонялка, библиотека

#1670 Newtask 1111555
  zdn/matoge2024/9/1111555.js
  zdn/matoge2024/9/main.js
Labels: ОГЭ, разработка, Уравнения и системы уравнений

#1783 refactoring-b9-3
  zdn/mat2014/B9/3.js
Labels: шаблон, Текстовые задачи

#1784 refactoring-b9-2
  zdn/mat2014/B9/2.js
Labels: шаблон, Текстовые задачи

#1779 Newtask 506299 2
  zdn/matege2024b/16/506299.js
  zdn/matege2024b/16/main.js
Labels: ЕГЭ-профиль, разработка, Текстовые задачи

#1703 Newtask 111557 new
  zdn/matoge2024/9/111557.js
  zdn/matoge2024/9/main.js
Labels: шаблон, ЕГЭ-профиль, разработка, Текстовые задачи

#1788 [zdn][new]-equation-fix #1657
  zdn/matoge2024/9/338482.js
  zdn/matoge2024/9/main.js
Labels: шаблон, ОГЭ, разработка, Уравнения и системы уравнений

#1594 New task10001583
  zdn/matoge2024/9/10001583.js
  zdn/matoge2024/9/main.js
Labels: шаблон, ОГЭ, разработка

#1790 [zdn][new]1115560 - equation - fix#1658
  zdn/matoge2024/9/1115560.js
  zdn/matoge2024/9/main.js
Labels: шаблон, ОГЭ, разработка, Уравнения и системы уравнений

#1792 drawRightAngle flag
  lib/canvas.js
Labels: Баг, библиотека

#1667 Newtask 338495
  zdn/matoge2024/9/338495.js
  zdn/matoge2024/9/main.js
Labels: ОГЭ, разработка, Уравнения и системы уравнений

#1673 Newtask 5997
  zdn/matege2024p/10/5997.js
  zdn/matege2024p/10/fipi.js
  zdn/matege2024p/10/main.js
Labels: ЕГЭ-профиль, разработка, Текстовые задачи
