Repository nickkolok/chas-ege, pull requests merged in 2025-04, with the labels that each got.

#2225 [zdn][new] 314120 - fix #1947
  zdn/matege2024b/15/314120.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2186 [zdn][new]-99605
  zdn/matege2024b/20/99605.js
  zdn/matege2024b/20/main.js
Labels: шаблон, разработка, Текстовые задачи, ЕГЭ-база

#2232 [zdn][new]-99604
  zdn/matege2024b/20/99604.js
  zdn/matege2024b/20/main.js
Labels: ЕГЭ-база

#2233 [zdn][new] 506423 - fix #1998
  zdn/matege2024b/21/506423.js
  zdn/matege2024b/21/main.js
Labels: Текстовые задачи, ЕГЭ-база, Задачи на смекалку

#2214 [zdn][new] 514913 - fix #1978
  zdn/matege2024b/21/514913.js
  zdn/matege2024b/21/main.js
Labels: Текстовые задачи, ЕГЭ-база, Задачи на смекалку
