Repository nickkolok/chas-ege, pull requests merged in 2025-09, with the labels that each got.

#2308 [zdn ] [new] - #2307
  zdn/matege2024b/12/6543.js
  zdn/matege2024b/12/main.js
Labels: Планиметрия, ЕГЭ-база

#2276 [zdn] [new] - ЕГЭ База - 12 - 215-218 - fix #2271
  zdn/matege2024b/12/11082.js
  zdn/matege2024b/12/main.js
Labels: Планиметрия, ЕГЭ-база

#2282 [zdn] [new] fix #2281
  zdn/matege2024b/12/10935.js
  zdn/matege2024b/12/main.js
Labels: Планиметрия, ЕГЭ-база

#2230 [zdn] [new] - resolve ЕГЭ База - 12 - 99-102 #2222
  zdn/matege2024b/12/2547.js
  zdn/matege2024b/12/main.js
Labels: Планиметрия, ЕГЭ-база

#2235 [zdn] [new] - resolve ЕГЭ База - 12 - 65-70 #2216
  zdn/matege2024b/12/6563.js
  zdn/matege2024b/12/main.js
Labels: Планиметрия, ЕГЭ-база

#2224 [zdn] [new] - resolve ЕГЭ База - 12 - 71-78 #2217
  zdn/matege2024b/12/506683.js
  zdn/matege2024b/12/main.js
Labels: Планиметрия, ЕГЭ-база

#2312 [zdn] [new] - fix #2311
  zdn/matege2024b/12/6623.js
  zdn/matege2024b/12/main.js
Labels: Планиметрия, ЕГЭ-база

#2694 [zdn][sym] -fix #2665 338238
  zdn/matoge2024/12/338238.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Математика-Геометрия, Симлинк

#2695 [zdn][sym] -fix #2666 98
  zdn/matoge2024/12/98.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Экономика, Симлинк

#2696 [zdn][sym] 506630 -fix #2667
  zdn/matoge2024/12/506630.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Физика, Симлинк

#2697 [zdn][sym] 510020 -fix #2673
  zdn/matoge2024/12/510020.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Физика, Симлинк

#2699 [zdn][sym] 523098 -fix #2676
  zdn/matoge2024/12/523098.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Физика, Симлинк

#2702 [zdn][sym] 311535 -fix #2679
  zdn/matoge2024/12/311535.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Математика-Геометрия, Симлинк

#2704 [zdn][sym] 506550 -fix #2682 #2683
  zdn/matoge2024/12/506550.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Математика-Геометрия, Симлинк

#2705 [zdn][sym] 510303 -fix #2684
  zdn/matoge2024/12/510303.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Математика-Геометрия, Симлинк

#2706 [zdn][sym] 506300 -fix #2685
  zdn/matoge2024/12/506300.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Математика-Геометрия, Симлинк

#2707 [zdn][sym] 530329 -fix #2686
  zdn/matoge2024/12/530329.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Математика-Геометрия, Симлинк

#2719 [zdn][new][sym] 510306 #2664
  zdn/matege2024b/4/510306.js
Labels: ОГЭ, Физика, Симлинк

#2717 [zdn][new][sym] 510314 #2663
  zdn/matege2024b/4/510314.js
Labels: ОГЭ, Физика, Симлинк

#2715 [zdn][new][sym] 513771 #2660
  zdn/matege2024b/4/513771.js
Labels: ОГЭ, Физика, Симлинк

#2713 [zdn][sym] 514383 -fix #2678
  zdn/matoge2024/12/514383.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Математика-Геометрия, Симлинк

#2332 [lib] [new] - segmentDivisionPoint
  lib/array_mt.js
Labels: библиотека

#1206 newTask_64485003
  zdn/matege2024p/2/64485003.js
  zdn/matege2024p/2/main.js
Labels: Вектора

#2724 [zdn][sym] 513771 #2660 #2715
  zdn/matoge2024/12/513771.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Физика, Симлинк

#2736 [zdn][new] 338296 -fix #2671
  zdn/matoge2024/12/338296.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Физика

#2734 [zdn][new] 338056 -fix #2670
  zdn/matoge2024/12/338056.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Физика

#2738 [zdn][new] 338089 -fix #2674
  zdn/matoge2024/12/338089.js
  zdn/matoge2024/12/fipi.js
  zdn/matoge2024/12/main.js
Labels: ОГЭ, Физика
