Repository nickkolok/chas-ege, pull requests merged in 2025-08, with the labels that each got.

#1884 [new] [zdn] - 525374
  zdn/matege2024b/5/525374.js
  zdn/matege2024b/5/fipi.js
  zdn/matege2024b/5/main.js
Labels: Теория вероятности(простая), ЕГЭ-база

#1043 newTask_314676
  zdn/matoge2024/11/314676.js
  zdn/matoge2024/11/main.js
Labels: ОГЭ

#2604 [zdn][new] 98 - fix #2558
  zdn/matege2024b/4/98.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Экономика

#2621 130825 new version flatten-shape-geometry
  package.json
Labels: библиотека

#2069 [zdn] [new] - 99617
  zdn/matege2024p/10/99617.js
  zdn/matege2024p/10/fipi.js
  zdn/matege2024p/10/main.js
Labels: Текстовые задачи

#1562 newTask_99591
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
  zdn/matege2024p/10/99591.js
Labels: ЕГЭ-профиль, Текстовые задачи

#2612 [zdn][new] 506300 -fix #2570 #2572
  zdn/matege2024b/4/506300.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Математика-Геометрия

#2609 [zdn][new] 510314 -fix #2592 #2600 #2601
  zdn/matege2024b/4/510314.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Физика

#2608 [zdn][new] 513771 -fix #2595 #2596
  zdn/matege2024b/4/513771.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Физика

#2294 [zdn] [new] - resolve #2293
  zdn/matege2024b/12/11252.js
  zdn/matege2024b/12/main.js
Labels: Планиметрия, ЕГЭ-база

#2623 [zdn][new] 509609 -fix #2589
  zdn/matege2024b/4/509609.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Физика

#2626 [zdn][new] 510020 -fix #2598
  zdn/matege2024b/4/510020.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Физика

#2632 [zdn][new] 506550 -fix #2566 #2567
  zdn/matege2024b/4/506550.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Математика-Геометрия

#2631 [zdn][new] 509589 -fix #2568
  zdn/matege2024b/4/509589.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Математика-Геометрия

#2622 [zdn][new] 506630 -fix #2586
  zdn/matege2024b/4/506630.js
Labels: ЕГЭ-база, Физика

#2231 [zdn] [new] - resolve ЕГЭ База - 12 - 103-108 109-114 #2223
  zdn/matege2024b/12/512423.js
  zdn/matege2024b/12/main.js
Labels: Планиметрия, ЕГЭ-база

#2619 [zdn][new] 506737 -fix #2602
  zdn/matege2024b/4/512937.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Физика

#2625 [zdn][new] 509769 -fix #2594
  zdn/matege2024b/4/509769.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Физика

#2614 [zdn][new] 530329 -fix #2580 #2581
  zdn/matege2024b/4/530329.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Математика-Арифметика

#2607 [znd][new] 523098 -fix #2591 #2593
  zdn/matege2024b/4/523098.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Физика

#2605 [zdn][new] 506387 - fix #2563
  zdn/matege2024b/4/506387.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Математика-Геометрия

#2630 [zdn][new] 512412 -fix #2582
  zdn/matege2024b/4/512412.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Математика-Геометрия

#2629 [zdn][new] 506301 -fix #2585
  zdn/matege2024b/4/506301.js
  zdn/matege2024b/4/main.js
Labels: ЕГЭ-база, Математика-Геометрия
