Repository nickkolok/chas-ege, pull requests merged in 2025-01, with the labels that each got.

#1886 maleNames and femaleNames
  lib/osnmas.js
Labels: библиотека

#1904 issue 514914
  zdn/matege2024b/21/514914.js
  zdn/matege2024b/21/main.js
Labels: ЕГЭ-база, Задачи на смекалку

#1905 issue 512408
  zdn/matege2024b/21/512508.js
  zdn/matege2024b/21/main.js
Labels: ЕГЭ-база, Задачи на смекалку

#1893 [new] [zdn] - 320171
  zdn/matege2024b/5/320171.js
  zdn/matege2024b/5/fipi.js
  zdn/matege2024b/5/main.js
Labels: Теория вероятности(простая), ЕГЭ-база

#1907 issue 77351
  zdn/matege2024b/21/77351.js
  zdn/matege2024b/21/main.js
Labels: ЕГЭ-база, Задачи на смекалку, Целые числа, Дроби

#1906 issue 77350
  zdn/matege2024b/21/77350.js
  zdn/matege2024b/21/main.js
Labels: ЕГЭ-база, Задачи на смекалку, Целые числа, Дроби

#1529 [lib] [new] - autoScale
  lib/func.js
Labels: библиотека

#1921 issue 515842
  zdn/matege2024b/21/515842.js
  zdn/matege2024b/21/main.js
Labels: ЕГЭ-база, Задачи на смекалку

#1950 issue 512414
  zdn/matege2024b/1/512414.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#1971 issue 505455
  zdn/matege2024b/1/505455.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#1959 issue 77338
  zdn/matege2024b/1/77338.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#1972 issue 282847
  zdn/matege2024b/1/282847.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#1974 [zdn][new] 323516 - fix #1813
  zdn/matege2024b/1/323516.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#1956 issue 77337
  zdn/matege2024b/1/77337.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#1973 [zdn][new] 282848 - fix #1814
  zdn/matege2024b/1/282848.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#1990 [zdn][new] 314867 -fix #1815
  zdn/matege2024b/1/314867.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#1970 issue 323512
  zdn/matege2024b/1/323512.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#2002 [zdn][new] - fix #1620
  zdn/matege2024p/10/5999.js
  zdn/matege2024p/10/fipi.js
  zdn/matege2024p/10/main.js
Labels: шаблон, ЕГЭ-профиль, разработка, Текстовые задачи

#1789 [zdn][new] - 50703502
  zdn/matege2024b/16/50703501.js
  zdn/matege2024b/16/main.js
Labels: разработка, Текстовые задачи

#1793 [zdn] [new] - 511648
  zdn/matege2024b/16/511648.js
  zdn/matege2024b/16/main.js
Labels: шаблон, разработка

#2003 [zdn][new] - equation - fix #1657
  zdn/matoge2024/9/311381.js
  zdn/matoge2024/9/main.js
Labels: шаблон, ОГЭ, разработка

#2004 [new][zdn] 77336 -fix #1817
  zdn/matege2024b/1/77336.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#2008 [zdn][new] 318581 -fix #1827
  zdn/matege2024b/1/318581.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#2012 newTask_99602
  zdn/matege2024p/10/99602.js
  zdn/matege2024p/10/fipi.js
  zdn/matege2024p/10/main.js
Labels: ЕГЭ-профиль, Текстовые задачи

#656 Рефакторинг zdn/mat2014/B11/9
  zdn/mat2014/B11/9.js
Labels: Требует доработки

#646 Рефакторинг zdn/mat2014/B11/1
  zdn/mat2014/B11/1.js
Labels: Требует доработки

#1895 [new] [zdn] - 510114
  zdn/matege2024b/5/510114.js
  zdn/matege2024b/5/fipi.js
  zdn/matege2024b/5/main.js
Labels: Теория вероятности(простая), ЕГЭ-база

#2030 isAlmostEqual
  lib/number.js
Labels: библиотека

#2005 [zdn][new] 531736 -fix #1820
  zdn/matege2024b/1/531736.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база
