Repository nickkolok/chas-ege, pull requests merged in 2025-03, with the labels that each got.

#2154 [zdn][new] 509648- fix #1962
  zdn/matege2024b/15/509648.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2155 [zdn][new] 506326 - fix #1961
  zdn/matege2024b/15/506326.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2152 [zdn][new] 137256 - fix #1938
  zdn/matege2024b/15/137256.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2156 [zdn][new] 506426 - fix #1957
  zdn/matege2024b/15/506426.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2157 [zdn][new] 77340 - fix #1953
  zdn/matege2024b/15/77340.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2158 [zdn][new] 77344 - fix #1954
  zdn/matege2024b/15/77344.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2159 [zdn][new] 26643 - fix #1943 and - fix #1958
  zdn/matege2024b/15/26643.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2168 [zdn][new] 77343 - fix #1949
  zdn/matege2024b/15/77343.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2170 [sh] [fix] - space after " - fix #1173
  sh/pechmat.js
Labels: библиотека

#2169 [zdn][new] 77365 - fix #1944
  zdn/matege2024b/15/77365.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2167 [zdn][new] 527676 - fix #1951
  zdn/matege2024b/15/527676.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2165 [zdn][new] 77349 - fix #1952
  zdn/matege2024b/15/77349.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2202 [zdn] [fix] - fix склонение цветов база 773322 #2192
  zdn/mat2014/B1/28.js
Labels: ЕГЭ-база

#2208 [zdn] - fix пробел база 323609 #2198
  zdn/mat2014/B1/25.js
Labels: ЕГЭ-база

#2181 [zdn][new] 510347 - fix #1942
  zdn/matege2024b/15/510347.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2215 [zdn][new] 514919 - fix #1987
  zdn/matege2024b/21/514919.js
  zdn/matege2024b/21/main.js
Labels: Текстовые задачи, ЕГЭ-база, Задачи на смекалку

#2207 [zdn] - fix пробел база 323512 #2197
  zdn/matege2024b/1/323512.js
Labels: ЕГЭ-база

#2206 [zdn] - fix #2196
  zdn/matege2024b/1/314867.js
Labels: ЕГЭ-база

#2205 [zdn] - пробелы база 77356 #2195
  zdn/matege2024b/1/77356.js
Labels: ЕГЭ-база

#2204 [zdn] - fix #2194
  zdn/matege2024b/1/77338.js
Labels: ЕГЭ-база

#2203 [zdn] - fix #2193
  zdn/matege2024b/1/77337.js
Labels: ЕГЭ-база

#1211 newTask_64485006
  zdn/matege2024p/2/64485006.js
  zdn/matege2024p/2/main.js
Labels: Вектора
