Repository nickkolok/chas-ege, pull requests merged in 2025-02, with the labels that each got.

#2007 [zdn][new] 77356 -fix #1823
  zdn/matege2024b/1/77356.js
  zdn/matege2024b/1/main.js
Labels: Текстовые задачи, ЕГЭ-база

#2035 issue 512414 -fix #1819 and #1818
  zdn/matege2024b/1/512414.js
Labels: Текстовые задачи, ЕГЭ-база

#2031 hasAlmostDuplicates
  lib/array_general.js
Labels: библиотека

#2077 [lib] [new] - randToChMin
  lib/number.js
Labels: библиотека

#2072 [zdn] [fix] - 26590
  zdn/matege2024p/10/26590.js
Labels: Текстовые задачи

#2074 [zdn] [fix] - 26592
  zdn/matege2024p/10/26592.js
Labels: Текстовые задачи

#1787 [zdn] [fix] - 320191
  zdn/mat2014/B6/320191.js
Labels: Теория вероятности(простая), Баг

#2073 [zdn] [fix] - 523375
  zdn/matege2024p/10/523375.js
Labels: Текстовые задачи

#2098 sklon_26592
  zdn/matege2024p/10/26592.js
Labels: ПРОВЕСТИ РЕВЬЮ

#2100 sklon_99614
  zdn/matege2024p/10/99614.js
Labels: ПРОВЕСТИ РЕВЬЮ

#2099 sklon_26597
  zdn/matege2024p/10/26597.js
Labels: ПРОВЕСТИ РЕВЬЮ

#2097 objectsFilledWithLiquid and objectsTransportingLiquids
  lib/decorations.js
Labels: библиотека

#2095 ChildNames
  lib/osnmas.js
Labels: библиотека

#1563 drawEllipse
  lib/canvas.js
Labels: библиотека

#2093 [zdn][new] 510679 -fix #1924
  zdn/matege2024b/15/510679.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2090 [zdn][new] 509768 -fix #1922
  zdn/matege2024b/15/509768.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2071 [zdn] [fix] - 5997
  zdn/matege2024p/10/5997.js
Labels: Текстовые задачи

#2091 [zdn][new] 511916 -fix #1923
  zdn/matege2024b/15/511916.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2101 [zdn][new] 515778 -fix #1926
  zdn/matege2024b/15/515778.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2105 [zdn][new] 512711 -fix #1928
  zdn/matege2024b/15/512711.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2113 [zdn][new] 518393 - fix #1931
  zdn/matege2024b/15/518393.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2102 [zdn][new] 506446 -fix #1927
  zdn/matege2024b/15/506446.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2106 [zdn][new] 317937 -fix #1929
  zdn/matege2024b/15/317937.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2094 [zdn][new] 506736 -fix #1925
  zdn/matege2024b/15/506736.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#1071 newTask_99584
  zdn/matege2023p/9/99584.js
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
Labels: Прогрессия

#2108 [zdn][new] 506569 -fix #1930
  zdn/matege2024b/15/506569.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#1070 newTask_99587
  zdn/matege2023p/9/99587.js
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
Labels: Прогрессия

#1068 newTask_99579
  zdn/matege2023p/9/99579.js
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
Labels: Прогрессия

#2114 [zdn][new] 514026 - fix #1932
  zdn/matege2024b/15/514026.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#1066 newTask_99581
  zdn/matege2023p/9/99581.js
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
Labels: Прогрессия

#1064 NewTask_99580
  zdn/matege2023p/9/99580.js
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
Labels: Прогрессия

#1072 newTask_99583
  zdn/matege2023p/9/99583.js
  zdn/matege2023p/9/fipi.js
  zdn/matege2023p/9/main.js
Labels: Прогрессия

#2129 [zdn][new] 506346 - fix #1933
  zdn/matege2024b/15/506346.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2132 [zdn][new] 137247 - fix #1937
  zdn/matege2024b/15/137247.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2140 [zdn][new] 77345 - fix #1934
  zdn/matege2024b/15/77345.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби

#2125 [zdn][new] 513810 - fix #1968 and - fix #1969
  zdn/matege2024b/15/513810.js
  zdn/matege2024b/15/main.js
Labels: Текстовые задачи, ЕГЭ-база, Дроби
